### ISSUE TITLE
Suggestion for biomes and structures

### ISSUE THREAD

**Issue by The-Nyla** [IrisDimensions/nether#3]
I'm not sure how this would work, but I think it would be a great idea if it were possible to port the "incendium" datapack generation into the Iris nether

Short description:

Incendium is a nether expansion datapack that adds multiple new biomes and structures to the nether, I believe the structures use procedural generation, so they should be able to be generated using iris.

Screenshots or other:

https://www.planetminecraft.com/data-pack/incendium-nether-expansion/

Optional Additional info:
The developer of Incendium has a discord, linked on the PMC page.

Also I'm not sure how viable this would be, I just realized that this would be a possibility, and thought it would be a really nice addition to the iris nether, if the if nether is ever finished/useable that is.

**Comment by ghost** [comment]
Why not just use that datapack for the nether and use iris for the overworld?

**Comment by The-Nyla** [comment]
I think it would probably be a slightly less-laggy alternative, and also just interesting to see that Iris would be able to do that.

**Comment by svdgoor** [comment]
I personally agree with Nowhere: does the potential customisability and performance outweigh the required work?

**Comment by svdgoor** [comment]
Especially compared to other dimensions that may be worked on, such as the end.

**Comment by The-Nyla** [comment]
Well an end generator would be amazing, and in my opinion much more so than a nether generator, because as amazing as improved nether generation and structures would be, there's not really anything that improves the end, and does it well. (Excluding the "BetterEnd" mod, but that is a mod, and would not be very useful on an un-modded server)

**Comment by The-Nyla** [comment]
There actually is one datapack that improves the end pretty well, but that still only adds a few biomes, and completely bugs out the dragon fight

**Comment by NextdoorPsycho** [comment]
Spigot does not support datapacks, and to our knowledge never will.
But i have the image pinned for when we get to the nether 👍
